language: java
sudo: true
 deploy:
 edge: true
 provider: cloudfoundry
 username: aris.s.kumar@verizon.com
 password: Tanish1#2
 api: https://api.run.pivotal.io
 organization: crisaris
 space: development
